// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1AyT9VT5D3UToU17-30rLcb9tCz1Eo_o',
    appId: '1:570232323077:web:4a942dd547f1b9d574706c',
    messagingSenderId: '570232323077',
    projectId: 'empathy-firebase',
    authDomain: 'empathy-firebase.firebaseapp.com',
    storageBucket: 'empathy-firebase.appspot.com',
    measurementId: 'G-RFNN2MVL6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiWyyi1L_QWN7upjJxUkQ5ssYXfG-Grho',
    appId: '1:570232323077:android:70ad4de235b42d9d74706c',
    messagingSenderId: '570232323077',
    projectId: 'empathy-firebase',
    storageBucket: 'empathy-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Q2duXYs-uSmciQLOLCvmHQ6NHJLnYQA',
    appId: '1:570232323077:ios:d7ffdb143eee688274706c',
    messagingSenderId: '570232323077',
    projectId: 'empathy-firebase',
    storageBucket: 'empathy-firebase.appspot.com',
    iosClientId:
        '570232323077-luch9r22l8g843gbl39g0a5cvh1n32hf.apps.googleusercontent.com',
    iosBundleId: 'com.empathy_flutter.empathyFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Q2duXYs-uSmciQLOLCvmHQ6NHJLnYQA',
    appId: '1:570232323077:ios:d7ffdb143eee688274706c',
    messagingSenderId: '570232323077',
    projectId: 'empathy-firebase',
    storageBucket: 'empathy-firebase.appspot.com',
    iosClientId:
        '570232323077-luch9r22l8g843gbl39g0a5cvh1n32hf.apps.googleusercontent.com',
    iosBundleId: 'com.empathy_flutter.empathyFlutter',
  );
}
